[project]
name = "f1calendar"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bottle",
    "icalendar",
    "requests",
    "waitress",
    "pillow"
]

[tool.setuptools.packages.find]
include = ["f1cal"]
